"""
Django settings for utility_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l@hu40qn4p1b^tnk%#jt)&7rr#j-ly_vl^im9)+1-#rvao*6c^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'utility_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'utility_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ==========================================
# DATABASE CONFIGURATION (Aiven Cloud & Local)
# ==========================================

# First, capture the host so we can check it
DB_HOST = os.environ.get('DB_HOST', 'localhost')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'utility_management'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Juliet@2005'), 
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}
# Apply different SSL rules depending on where the app is running
if DB_HOST == 'localhost' or DB_HOST == '127.0.0.1':
    # Local development: Ignore strict SSL verification
    DATABASES['default']['OPTIONS'] = {
        'ssl': {'cert_reqs': 0}
    }
else:
    # Aiven Cloud (or production): Enforce strict SSL using the CA certificate
    DATABASES['default']['OPTIONS'] = {
        'ssl': {
            'ca': os.path.join(BASE_DIR, 'ca.pem')
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'core.User'

import os

# Media files (uploaded photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# M-Pesa Daraja Sandbox Configuration
# ==========================================
# M-PESA CONFIGURATION (Vercel & Local)
# ==========================================
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', 'NJDK1YqtCR9mh0RHIZAI2Axr7QtozBxnyWMEmSBGZPswZihH')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', 'gCfGqL3pdGETEzZDGrcYWAsvfdLhdLdEnlxMwPGMbwZhBX39zsZWdHfhyx9BTJUM')
MPESA_SHORTCODE = os.environ.get('MPESA_SHORTCODE', '174379') # Sandbox default
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY', 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919')
MPESA_CALLBACK_URL = os.environ.get('MPESA_CALLBACK_URL', 'https://miguelina-interdestructive-soothingly.ngrok-free.dev/mpesa/webhook/5/') 

LOGIN_URL = '/'

LOGIN_REDIRECT_URL = 'manager_dashboard'

# Email Configuration
# For development, we'll use console backend (prints emails to terminal)
# For production, configure with actual SMTP settings

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production with Gmail (example):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'SUMS <your-email@gmail.com>'

# For now, console backend (emails print to console)
DEFAULT_FROM_EMAIL = 'SUMS <noreply@sums.com>'

# Africa's Talking SMS Configuration
# Get credentials from https://account.africastalking.com/

AFRICASTALKING_USERNAME = 'sandbox'  # Use 'sandbox' for testing, your username for production
AFRICASTALKING_API_KEY = 'atsk_39c8554a992c0fe5d7795db16e16f26806772d199ae5fe90c9e4df34e8e0d3bb8d8ac04a'  # Get from Africa's Talking dashboard
AFRICASTALKING_SENDER_ID = 'SUMS'  # Short code or sender name (max 11 characters)

# For production:
# AFRICASTALKING_USERNAME = 'your_username'
# AFRICASTALKING_API_KEY = 'your_production_api_key'