# Generated by Django 6.0.3 on 2026-03-29 19:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_value', models.DecimalField(decimal_places=2, help_text='Current meter reading value', max_digits=10)),
                ('reading_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when reading was taken')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of meter for verification', null=True, upload_to='meter_readings/')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, help_text='Calculated consumption since last reading', max_digits=10)),
                ('is_anomaly', models.BooleanField(default=False, help_text='Flagged if consumption pattern is unusual')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this reading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meter')),
                ('recorded_by', models.ForeignKey(help_text='Property manager who recorded this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_date'],
            },
        ),
    ]
