# Generated by Django 6.0.3 on 2026-04-06 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meterreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current balance (positive = debt, negative = credit)', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time balance was updated')),
                ('tenant', models.OneToOneField(help_text='Tenant this balance belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='account_balance', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FixedCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(help_text="Name of the charge (e.g., 'Garbage Collection')", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed amount charged monthly', max_digits=10)),
                ('effective_from', models.DateField(help_text='Date from which this charge becomes active')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this charge is currently applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(help_text='Property manager who owns this charge', on_delete=django.db.models.deletion.CASCADE, to='core.propertymanager')),
            ],
            options={
                'ordering': ['charge_name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice identifier (e.g., INV-2026-03-001)', max_length=50, unique=True)),
                ('invoice_date', models.DateField(help_text='Date invoice was generated')),
                ('due_date', models.DateField(help_text='Payment deadline')),
                ('billing_period', models.CharField(help_text="Billing period (e.g., 'March 2026')", max_length=20)),
                ('water_units', models.DecimalField(decimal_places=2, default=0, help_text='Water consumption in units', max_digits=10)),
                ('water_rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate per water unit', max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, help_text='Total water charge (units × rate)', max_digits=10)),
                ('electricity_units', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Electricity consumption in units', max_digits=10, null=True)),
                ('electricity_rate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rate per electricity unit', max_digits=10, null=True)),
                ('electricity_charge', models.DecimalField(decimal_places=2, default=0, help_text='Total electricity charge (units × rate)', max_digits=10)),
                ('total_fixed_charges', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all fixed monthly charges', max_digits=10)),
                ('fixed_charges_breakdown', models.JSONField(default=dict, help_text='Breakdown of fixed charges {name: amount}')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Sum of all charges before previous balance', max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding balance from previous invoices (negative = credit)', max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, help_text='Final amount to be paid (subtotal + previous_balance)', max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', help_text='Current payment status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(help_text='User who generated this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant at time of invoice generation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tenant')),
                ('unit', models.ForeignKey(help_text='Unit this invoice is for', on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Date payment was received')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('BANK', 'Bank Transfer')], help_text='How payment was made', max_length=20)),
                ('mpesa_reference', models.CharField(blank=True, help_text='M-Pesa transaction code (e.g., QGJ4X7Y8ZW)', max_length=100, null=True)),
                ('mpesa_phone', models.CharField(blank=True, help_text='Phone number used for M-Pesa', max_length=15, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.invoice')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('WATER', 'Water'), ('ELECTRICITY', 'Electricity')], help_text='Type of utility this rate applies to', max_length=15)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='Cost per unit (e.g., KES 50 per m³ of water)', max_digits=10)),
                ('effective_from', models.DateField(help_text='Date from which this rate becomes active')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(help_text='Property manager who owns this rate configuration', on_delete=django.db.models.deletion.CASCADE, to='core.propertymanager')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
