# Generated by Django 6.0.3 on 2026-04-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accountbalance_fixedcharge_invoice_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified Valid'), ('REJECTED', 'Rejected - Needs Recount')], default='VERIFIED', help_text='Verification status for anomaly triage', max_length=10),
        ),
    ]
