# Generated by Django 6.0.3 on 2026-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meterreading_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate tenant instead of deleting'),
        ),
    ]
