# Generated by Django 6.0.3 on 2026-04-20 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications (e.g., 0712345678)', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.unit'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
