# Generated by Django 6.0.3 on 2026-04-20 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tenant_phone_number_alter_tenant_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(help_text='20-digit electricity token number', max_length=50)),
                ('units', models.DecimalField(decimal_places=2, help_text='Number of kWh units purchased', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid for the token (KES)', max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='When the token was logged')),
                ('expiry_date', models.DateField(blank=True, help_text='Token expiry date (if applicable)', null=True)),
                ('vendor', models.CharField(blank=True, help_text='Vendor/source of token (e.g., Kenya Power, M-Pesa)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the token')),
                ('tenant', models.ForeignKey(help_text='Tenant who purchased the token', on_delete=django.db.models.deletion.CASCADE, related_name='electricity_tokens', to='core.tenant')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_token_logging', models.BooleanField(default=False, help_text='Enable electricity token logging feature')),
                ('enable_sms_notifications', models.BooleanField(default=True, help_text='Receive SMS notifications for invoices and payments')),
                ('enable_email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('show_consumption_alerts', models.BooleanField(default=True, help_text='Show alerts for high consumption')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(help_text='Tenant these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.tenant')),
            ],
        ),
    ]
