# Generated by Django 6.0.3 on 2026-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_maintenancerequest_maintenancemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('PROPERTY_MANAGER', 'Property Manager'), ('TENANT', 'Tenant')], max_length=20),
        ),
    ]
