# Generated by Django 6.0.3 on 2026-05-30 22:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='electricity_anomaly_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Maximum normal electricity consumption per reading period', max_digits=10),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='water_anomaly_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum normal water consumption per reading period', max_digits=10),
        ),
    ]
