# Generated by Django 6.0.3 on 2026-06-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_propert_1db7c3_idx',
            old_name='core_auditl_propert_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_categor_8b1585_idx',
            old_name='core_auditl_categor_6e0b0a_idx',
        ),
    ]
